pages: false
files: false

fields:
  hgeneral:
    label: Général
    type: headline

  title:
    label: Titre du site
    type:  text
    translate: false

  mailto:
    label: Email d'administration
    type: email
    translate: false

  gseo:
    label: SEO
    type: headline

  description:
    label: Description du site
    type: textarea
    buttons: false
    translate: false
    icon: search
    help: Utilisé par les moteurs de recherches et les réseaux sociaux
    validate:
      maxLength: 150

  keywords:
    label: Mots-clefs
    translate: false
    type: tags
    help: Utilisé par les moteurs de recherches et les réseaux sociaux

  redirections:
    label: Redirections spécifiques
    type: structure
    style: table
    translate: false
    fields:
      from:
        label: Ancienne URL
        type: url
        required: true
      to:
        label: Nouvelle page
        type: page
        required: true

  hfooter:
    label: Footer
    type: headline

  social:
    label: Liens sociaux
    type: structure
    style: table
    fields:
      text:
        label: Texte du lien
        type: text
        icon: font
      url:
        icon: link
        label: URL du lien
        type: text
      blank:
        label: Ouvre un nouvel onglet
        icon: external-link
        type: toggle
        text: yes/no

  misc:
    label: Liens additionnels
    type: structure
    style: table
    fields:
      text:
        label: Texte du lien
        type: text
        icon: font
      url:
        icon: link
        label: URL du lien
        type: text
      blank:
        label: Ouvre un nouvel onglet
        icon: external-link
        type: toggle
        text: yes/no
